service: mtgbot


provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-central-1
  memorySize: 256
  timeout: 3
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    ELASTIC_ENDPOINT: ${env:ELASTIC_ENDPOINT}

package:
  patterns:
    - "*"
    - "src/**"

functions:
  post:
    handler: serverless.search
    events:
      - http:
          path: scryfall_search_inline
          method: post
          cors: true
