service: mtgbot


provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-central-1
  memorySize: 128
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}


functions:
  post:
    handler: handler.search
    events:
      - http:
          path: scryfall_search_inline
          method: post
          cors: true
    package:
      include:
        handler.py
        vendored/**
      exclude:
        vendored/*.dist-info/**